language: python
python:
  - "3.6"

before_install:
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install git

install:
  - pip install -e .
  - pip install pytest
script:
  - py.test
