#!/bin/sh

gitdir="$(git rev-parse --git-dir)"
hook="$gitdir/hooks/post-commit"

author_date=$(git log -1 --format=%ad)
committer_date=$(git log -1 --format=%cd)
date=$(git-privacy -getstamp -gitdir "$(git rev-parse --show-toplevel)")

[ -x $hook ] && chmod -x $hook

GIT_COMMITTER_DATE="$date" git commit --amend --date "$date" -C HEAD -n

chmod +x $hook

git-privacy -store -gitdir $(git rev-parse --show-toplevel) -hexsha $(git rev-parse HEAD) -a_date "$author_date" -c_date "$committer_date"
